# Site settings
title: Homein
description: > # this means to ignore newlines until "baseurl:"
  A small site to help anyone and everyone find a place to live or let the world know their place is available to buy or rent.
baseurl: "/homein" # the subpath of your site, e.g. /blog/
github_username:  daraul

# Build settings
markdown: kramdown
